---
stages:
- name: Build
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: go-build
    type: builder
    artifact_dir: ./
    build_type: shell
    script: |-
      #!/bin/bash
      wget https://raw.githubusercontent.com/canha/golang-tools-install-script/master/main.sh >/dev/null 2>&1
      bash goinstall.sh --64
      source $HOME/.profile
      make
- name: Deploy
  inputs:
  - type: job
    stage: Build
    job: go-build
  triggers:
  - type: stage
  jobs:
  - name: Deploy
    type: deployer
    target:
      url: https://api.ng.bluemix.net
      organization: simon_kaegi@ca.ibm.com
      space: dev
      application: go-hello-world-skaegi-1618
    script: |-
      #!/bin/bash
      cf push
      # view logs
      #cf logs "${CF_APP}" --recent
